import { Setting } from "@/app/Types/TypesTest/setting.types";

export const settingConstants: Setting[] = [
    {
        DataSet_id: 8,
        age: "60 เดือน",
        banner: "1753334695353-461019946.jpg",
        SidePro: [
            {
                SidePro_id: 15,
                Name: "1",
                status: "ACTIVE",
                DataSet_id: 8,
                Proposition: [
                    {
                        Proposition_id: 20,
                        Point: "1",
                        Proposition: "คำถามที่ 1 ",
                        Propositionimage: null,
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 15,
                    },
                    {
                        Proposition_id: 21,
                        Point: "2",
                        Proposition: "คำถามที่ 2",
                        Propositionimage: null,
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 15,
                    },
                    {
                        Proposition_id: 22,
                        Point: "3",
                        Proposition: "คำถามที่ 3",
                        Propositionimage: null,
                        Answerimage: 1,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 15,
                    },
                ],
            },
            {
                SidePro_id: 16,
                Name: "2",
                status: "ACTIVE",
                DataSet_id: 8,
                Proposition: [
                    {
                        Proposition_id: 23,
                        Point: "1",
                        Proposition: "คำถามที่ 1",
                        Propositionimage: "",
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 16,
                    },
                ],
            },
            {
                SidePro_id: 17,
                Name: "3",
                status: "ACTIVE",
                DataSet_id: 8,
                Proposition: [
                    {
                        Proposition_id: 24,
                        Point: "1",
                        Proposition: "คำถามที่ 1",
                        Propositionimage: null,
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 17,
                    },
                ],
                Vdo: [
                    {
                        Side_id: 30,
                        Name: "GM",
                        status: "ACTIVE",
                        DataSet_id: 8,
                        VDO: [
                            {
                                VDO_id: 7,
                                Proposition: "เดินต่อเท้า",
                                url: "1753364197054-722857704.mp4",
                                Answer: 1,
                                status: "ACTIVE",
                                Side_id: 30,
                            },
                        ],
                    },
                    {
                        Side_id: 31,
                        Name: "FM",
                        status: "ACTIVE",
                        DataSet_id: 8,
                        VDO: [
                            {
                                VDO_id: 11,
                                Proposition: "เดินต่อเท้า",
                                url: "1753364197054-722857704.mp4",
                                Answer: 1,
                                status: "ACTIVE",
                                Side_id: 30,
                            },
                        ],
                    },
                    {
                        Side_id: 32,
                        Name: "RL",
                        status: "ACTIVE",
                        DataSet_id: 8,
                        VDO: [
                            {
                                VDO_id: 10,
                                Proposition: "เดินต่อเท้า",
                                url: "1753364197054-722857704.mp4",
                                Answer: 1,
                                status: "ACTIVE",
                                Side_id: 30,
                            },
                        ],
                    },
                    {
                        Side_id: 33,
                        Name: "EL",
                        status: "ACTIVE",
                        DataSet_id: 8,
                        VDO: [
                            {
                                VDO_id: 8,
                                Proposition: "เดินต่อเท้า",
                                url: "1753364197054-722857704.mp4",
                                Answer: 1,
                                status: "ACTIVE",
                                Side_id: 30,
                            },
                        ],
                    },
                    {
                        Side_id: 34,
                        Name: "PS",
                        status: "ACTIVE",
                        DataSet_id: 8,
                        VDO: [
                            {
                                VDO_id: 9,
                                Proposition: "เดินต่อเท้า",
                                url: "1753364197054-722857704.mp4",
                                Answer: 1,
                                status: "ACTIVE",
                                Side_id: 30,
                            },
                        ],
                    },
                ],
            },
            {
                SidePro_id: 18,
                Name: "4",
                status: "ACTIVE",
                DataSet_id: 8,
                Proposition: [
                    {
                        Proposition_id: 25,
                        Point: "1",
                        Proposition: "คำถามที่ 1",
                        Propositionimage: null,
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 18,
                    },
                    {
                        Proposition_id: 26,
                        Point: "2",
                        Proposition: "คำถามที่ 2",
                        Propositionimage: null,
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 18,
                    },
                ],
            },
        ],
    },
    {
        DataSet_id: 8,
        age: "12 เดือน",
        banner: "1753334695353-461019946.jpg",
        SidePro: [
            {
                SidePro_id: 15,
                Name: "1",
                status: "ACTIVE",
                DataSet_id: 8,
                Proposition: [
                    {
                        Proposition_id: 20,
                        Point: "1",
                        Proposition: "คำถามที่ 1 ",
                        Propositionimage: null,
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 15,
                    },
                    {
                        Proposition_id: 21,
                        Point: "2",
                        Proposition: "คำถามที่ 2",
                        Propositionimage: null,
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 15,
                    },
                    {
                        Proposition_id: 22,
                        Point: "3",
                        Proposition: "คำถามที่ 3",
                        Propositionimage: null,
                        Answerimage: 1,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 15,
                    },
                ],
            },
            {
                SidePro_id: 16,
                Name: "2",
                status: "ACTIVE",
                DataSet_id: 8,
                Proposition: [
                    {
                        Proposition_id: 23,
                        Point: "1",
                        Proposition: "คำถามที่ 1",
                        Propositionimage: "",
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 16,
                    },
                ],
            },
            {
                SidePro_id: 17,
                Name: "3",
                status: "ACTIVE",
                DataSet_id: 8,
                Proposition: [
                    {
                        Proposition_id: 24,
                        Point: "1",
                        Proposition: "คำถามที่ 1",
                        Propositionimage: null,
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 17,
                    },
                ],
                Vdo: [
                    {
                        Side_id: 30,
                        Name: "GM",
                        status: "ACTIVE",
                        DataSet_id: 8,
                        VDO: [
                            {
                                VDO_id: 7,
                                Proposition: "เดินต่อเท้า",
                                url: "1753364197054-722857704.mp4",
                                Answer: 1,
                                status: "ACTIVE",
                                Side_id: 30,
                            },
                        ],
                    },
                    {
                        Side_id: 31,
                        Name: "FM",
                        status: "ACTIVE",
                        DataSet_id: 8,
                        VDO: [
                            {
                                VDO_id: 11,
                                Proposition: "เดินต่อเท้า",
                                url: "1753364197054-722857704.mp4",
                                Answer: 1,
                                status: "ACTIVE",
                                Side_id: 30,
                            },
                        ],
                    },
                    {
                        Side_id: 32,
                        Name: "RL",
                        status: "ACTIVE",
                        DataSet_id: 8,
                        VDO: [
                            {
                                VDO_id: 10,
                                Proposition: "เดินต่อเท้า",
                                url: "1753364197054-722857704.mp4",
                                Answer: 1,
                                status: "ACTIVE",
                                Side_id: 30,
                            },
                        ],
                    },
                    {
                        Side_id: 33,
                        Name: "EL",
                        status: "ACTIVE",
                        DataSet_id: 8,
                        VDO: [
                            {
                                VDO_id: 8,
                                Proposition: "เดินต่อเท้า",
                                url: "1753364197054-722857704.mp4",
                                Answer: 1,
                                status: "ACTIVE",
                                Side_id: 30,
                            },
                        ],
                    },
                    {
                        Side_id: 34,
                        Name: "PS",
                        status: "ACTIVE",
                        DataSet_id: 8,
                        VDO: [
                            {
                                VDO_id: 9,
                                Proposition: "เดินต่อเท้า",
                                url: "1753364197054-722857704.mp4",
                                Answer: 1,
                                status: "ACTIVE",
                                Side_id: 30,
                            },
                        ],
                    },
                ],
            },
            {
                SidePro_id: 18,
                Name: "4",
                status: "ACTIVE",
                DataSet_id: 8,
                Proposition: [
                    {
                        Proposition_id: 25,
                        Point: "1",
                        Proposition: "คำถามที่ 1",
                        Propositionimage: null,
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 18,
                    },
                    {
                        Proposition_id: 26,
                        Point: "2",
                        Proposition: "คำถามที่ 2",
                        Propositionimage: null,
                        Answerimage: 0,
                        Answer: [
                            { answer: "ทดสอบ 1", isTrue: 1 },
                            { answer: "ทดสอบ 2", isTrue: 0 },
                            { answer: "ทดสอบ 3", isTrue: 0 },
                            { answer: "ทดสอบ 4", isTrue: 0 },
                            { answer: "ทดสอบ 5", isTrue: 0 },
                            { answer: "ทดสอบ 6", isTrue: 0 },
                        ],
                        status: "ACTIVE",
                        SidePro_id: 18,
                    },
                ],
            },
        ],
    },
];
